# Site settings
title: Watercourse Counseling
email: info@watercoursecounseling.org
phone: 612-822-8227
fax: 612-825-4204
address: 3548 Bryant Ave S, Minneapolis, MN 55408
description: > # this means to ignore newlines until "baseurl:"
  Watercourse Counseling Center, founded in 1999, is a nonprofit agency established
  to improve the emotional health of our diverse community.
baseurl: "/watercourse"
url: "http://watercoursecounseling.org" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
facebook_username: watercoursecounseling

# Build settings
markdown: kramdown
